--- 
branches: 
  only: 
    - develop
install: 
  - "pip install -r requirements.txt"
language: python
# notifications: 
#   email: 
#     on_failure: always
#     on_success: never
#     recipients: 
#       - abavabaraba@gmail.com
python: 
  - "3.9"
script: 
  - "pytest PARTtest_uat.py"
before_script:
  - "python aws_ios.py"
after_script:
  - "sleep 1"
  - "python email_scr.py"
