--- 
branches: 
  only: 
    - feature/poc
install: 
  - "pip install -r android/requirements.txt"
language: python
notifications: 
  email: 
    on_failure: always
    on_success: never
    recipients: 
      - abavabaraba@gmail.com
python: 
  - "3.9"
script: 
  - "pytest android/PARTtest_uat.py"