from appium.webdriver.common.mobileby import By
from appium.webdriver.common.mobileby import MobileBy

RETAILERS_TOP_CAROUSEL_ITEM_TITLES = "//XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell[1]/XCUIElementTypeOther/XCUIElementTypeCollectionView/XCUIElementTypeCell/XCUIElementTypeOther/XCUIElementTypeButton/XCUIElementTypeStaticText"

